SELECT *
FROM (SELECT AA.ANIMAL_ID AS ANIMAL_ID  , AA.NAME AS NAME
FROM ANIMAL_INS AA, ANIMAL_OUTS BB
WHERE AA.ANIMAL_ID  = BB.ANIMAL_ID 
ORDER BY TO_CHAR(BB.DATETIME, 'YYYYMMDD') - TO_CHAR(AA.DATETIME, 'YYYYMMDD') DESC
)
WHERE ROWNUM <= 2