-- 코드를 입력하세요
SELECT A.CART_ID 
FROM ( SELECT DISTINCT CART_ID FROM CART_PRODUCTS WHERE NAME= '우유' ) A,
     ( SELECT DISTINCT CART_ID FROM CART_PRODUCTS WHERE NAME= '요거트' ) B
WHERE A.CART_ID = B.CART_ID
ORDER BY A.CART_ID
;